// Copies the pinned rrweb-player dist into public/assets (served by the ASSETS binding).
// Run after changing the rrweb-player version: `npm run vendor:player`.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs'
const dist = 'node_modules/rrweb-player/dist/'
const { version } = JSON.parse(readFileSync('node_modules/rrweb-player/package.json', 'utf8'))
mkdirSync('public/assets', { recursive: true })
for (const f of readdirSync('public/assets')) if (f.startsWith('rrweb-player.')) rmSync(`public/assets/${f}`)
const strip = (s) => s.replace(/\n\/\/# sourceMappingURL=.*$/m, '\n').replace(/\/\*# sourceMappingURL=.*?\*\//, '')
writeFileSync(`public/assets/rrweb-player.${version}.js`, strip(readFileSync(dist + 'rrweb-player.umd.min.cjs', 'utf8')))
writeFileSync(`public/assets/rrweb-player.${version}.css`, strip(readFileSync(dist + 'style.min.css', 'utf8')))
writeFileSync('src/player-version.ts', `// Generated by scripts/vendor-player.mjs. Do not edit.\nexport const PLAYER_VERSION = '${version}'\n`)
console.log('vendored rrweb-player', version)
